security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    foo: { password: test }
        user_db:
            entity: { class: App\Entity\User, property: username }
                

    firewalls:
        secured_area:
            anonymous: ~
            form_login:
                # target_path_parameter: /user
                login_path: login
                check_path: login
                always_use_default_target_path: true
                # default_target_path:            /user
                provider: chain_provider
            # http_basic:
            #     realm: 'Secured Demo Area'
            #     provider: in_memory
            
        
            
            
            logout:
                path:   /logout
                target: /
                invalidate_session: true
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }